### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by keizer7** [LLIAJIYH/AStar-Algorithm#1]
Why can't I run your code, and I always get an error when I can't find the path

**Comment by keizer7** [comment]
![image](https://github.com/bayram-dev/AStar-Algorithm/assets/115202553/642fd867-05de-40be-bde8-ee1debc78276)
like this error

**Comment by bayram-dev** [comment]
Hello, you can pass a .map file as an argument for binary and it will calculate path

```
bayram@debian:~/work/test/AStar-Algorithm/build$ ./AStar ../Data/2.map 
(25,9)->(26,10)->(27,11)->(28,12)->(29,13)->(30,14)->(31,15)->(32,16)
```

**Comment by bayram-dev** [comment]
last 6 lines in every `.map` file mean:
start.x
start.y
goal.x
goal.y
true_cardinal_cost
true_diagonal_cost;

**Comment by bayram-dev** [comment]
Closing as completed, no additions in 7days
